import type { Event, Student, Registration, Feedback } from "./types"

export const mockStudents: Student[] = [
  {
    id: "student-1",
    name: "Alice Johnson",
    email: "alice.johnson@university.edu",
    registrations: ["event-1", "event-2", "event-3"],
    attendedEvents: ["event-1", "event-2"],
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "student-2",
    name: "Bob Smith",
    email: "bob.smith@university.edu",
    registrations: ["event-1", "event-3"],
    attendedEvents: ["event-1"],
    createdAt: "2024-01-16T10:00:00Z",
  },
  {
    id: "student-3",
    name: "Carol Davis",
    email: "carol.davis@university.edu",
    registrations: ["event-2", "event-3"],
    attendedEvents: ["event-2", "event-3"],
    createdAt: "2024-01-17T10:00:00Z",
  },
  {
    id: "student-4",
    name: "David Wilson",
    email: "david.wilson@university.edu",
    registrations: ["event-1", "event-2"],
    attendedEvents: ["event-1", "event-2"],
    createdAt: "2024-01-18T10:00:00Z",
  },
  {
    id: "student-5",
    name: "Emma Brown",
    email: "emma.brown@university.edu",
    registrations: ["event-3"],
    attendedEvents: [],
    createdAt: "2024-01-19T10:00:00Z",
  },
]

export const mockRegistrations: Registration[] = [
  { id: "reg-1", studentId: "student-1", eventId: "event-1", registeredAt: "2024-12-01T10:00:00Z", attended: true },
  { id: "reg-2", studentId: "student-1", eventId: "event-2", registeredAt: "2024-12-02T10:00:00Z", attended: true },
  { id: "reg-3", studentId: "student-1", eventId: "event-3", registeredAt: "2024-12-03T10:00:00Z", attended: false },
  { id: "reg-4", studentId: "student-2", eventId: "event-1", registeredAt: "2024-12-01T11:00:00Z", attended: true },
  { id: "reg-5", studentId: "student-2", eventId: "event-3", registeredAt: "2024-12-03T11:00:00Z", attended: false },
  { id: "reg-6", studentId: "student-3", eventId: "event-2", registeredAt: "2024-12-02T12:00:00Z", attended: true },
  { id: "reg-7", studentId: "student-3", eventId: "event-3", registeredAt: "2024-12-03T12:00:00Z", attended: true },
  { id: "reg-8", studentId: "student-4", eventId: "event-1", registeredAt: "2024-12-01T13:00:00Z", attended: true },
  { id: "reg-9", studentId: "student-4", eventId: "event-2", registeredAt: "2024-12-02T13:00:00Z", attended: true },
  { id: "reg-10", studentId: "student-5", eventId: "event-3", registeredAt: "2024-12-03T14:00:00Z", attended: false },
]

export const mockFeedback: Feedback[] = [
  {
    id: "feedback-1",
    studentId: "student-1",
    eventId: "event-1",
    rating: 5,
    comments: "Excellent workshop! Learned a lot about React.",
    submittedAt: "2024-12-05T15:00:00Z",
  },
  {
    id: "feedback-2",
    studentId: "student-1",
    eventId: "event-2",
    rating: 4,
    comments: "Great fest, amazing performances!",
    submittedAt: "2024-12-12T16:00:00Z",
  },
  {
    id: "feedback-3",
    studentId: "student-2",
    eventId: "event-1",
    rating: 4,
    comments: "Very informative session.",
    submittedAt: "2024-12-05T17:00:00Z",
  },
  {
    id: "feedback-4",
    studentId: "student-3",
    eventId: "event-2",
    rating: 5,
    comments: "Best cultural fest ever!",
    submittedAt: "2024-12-12T18:00:00Z",
  },
  {
    id: "feedback-5",
    studentId: "student-3",
    eventId: "event-3",
    rating: 3,
    comments: "Good seminar but could be more interactive.",
    submittedAt: "2024-12-20T19:00:00Z",
  },
  {
    id: "feedback-6",
    studentId: "student-4",
    eventId: "event-1",
    rating: 5,
    comments: "Perfect introduction to modern web development.",
    submittedAt: "2024-12-05T20:00:00Z",
  },
  {
    id: "feedback-7",
    studentId: "student-4",
    eventId: "event-2",
    rating: 4,
    comments: "Loved the music and dance performances.",
    submittedAt: "2024-12-12T21:00:00Z",
  },
]

export const mockEvents: Event[] = [
  {
    id: "event-1",
    name: "Tech Fest",
    type: "Fest",
    date: "2025-09-12",
    time: "10:00",
    location: "Main Campus Ground",
    description:
      "Annual technology festival featuring innovation showcases, tech competitions, startup exhibitions, and networking opportunities with industry leaders.",
    maxCapacity: 500,
    registrations: mockRegistrations.filter((r) => r.eventId === "event-1"),
    attendees: ["student-1", "student-2", "student-4"],
    feedback: mockFeedback.filter((f) => f.eventId === "event-1"),
    createdAt: "2024-11-15T10:00:00Z",
    status: "upcoming",
  },
  {
    id: "event-2",
    name: "AI Bootcamp",
    type: "Workshop",
    date: "2025-09-15",
    time: "14:00",
    location: "Computer Science Lab 201",
    description:
      "Intensive hands-on workshop covering machine learning fundamentals, neural networks, and practical AI applications using Python and TensorFlow.",
    maxCapacity: 40,
    registrations: mockRegistrations.filter((r) => r.eventId === "event-2"),
    attendees: ["student-1", "student-3", "student-4"],
    feedback: mockFeedback.filter((f) => f.eventId === "event-2"),
    createdAt: "2024-11-20T10:00:00Z",
    status: "upcoming",
  },
  {
    id: "event-3",
    name: "Cultural Night",
    type: "Fest",
    date: "2025-09-21",
    time: "19:00",
    location: "Main Auditorium",
    description:
      "Celebrate diversity with an evening of music, dance, poetry, and cultural performances representing different traditions and communities on campus.",
    maxCapacity: 300,
    registrations: mockRegistrations.filter((r) => r.eventId === "event-3"),
    attendees: ["student-3"],
    feedback: mockFeedback.filter((f) => f.eventId === "event-3"),
    createdAt: "2024-11-25T10:00:00Z",
    status: "upcoming",
  },
  {
    id: "event-4",
    name: "Design Thinking Workshop",
    type: "Workshop",
    date: "2025-09-24",
    time: "13:00",
    location: "Innovation Hub Room 105",
    description:
      "Learn human-centered design methodology through interactive exercises, brainstorming sessions, and prototype development for real-world problems.",
    maxCapacity: 25,
    registrations: [],
    attendees: [],
    feedback: [],
    createdAt: "2024-11-28T10:00:00Z",
    status: "upcoming",
  },
]
